# Generated by Django 3.0 on 2019-12-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
